apiVersion: v1
kind: Service
metadata:
  namespace: sagas-namespace
  name: order-service
  labels:
    app: order-app
spec:
  type: NodePort
  ports:
  - port: 5051
    nodePort: 30001
    protocol: TCP
    targetPort: 5051
  selector:
    app: order-app