apiVersion: v1
kind: Service
metadata:
  namespace: sagas-namespace
  name: payment-service
  labels:
    app: payment-app
spec:
  type: NodePort
  ports:
  - port: 5050
    nodePort: 30000
    protocol: TCP
    targetPort: 5050
  selector:
    app: payment-app