apiVersion: v1
kind: Service
metadata:
  namespace: sagas-namespace
  name: stock-service
  labels:
    app: stock-app
spec:
  type: NodePort
  ports:
  - port: 5052
    nodePort: 30002
    protocol: TCP
    targetPort: 5052
  selector:
    app: stock-app