apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: sagas-namespace
  labels:
    app: kafka
spec:
  type: NodePort
  ports:
  - port: 9092
    nodePort: 30092
    protocol: TCP
    name: plaintext
  - port: 9999
    name: jmx
  selector:
    app: kafka